#pragma once

#include <Global.h>
#include <String/StringUtils.h>
#include <String/Formatter.h>
#include <Exception/Exception.h>
#include <AtlCom/CoInitialize.h>
#include <Registry/Registry.h>
#include <Msi/Msi.h>
#include <MsiShim/MsiShim.h>
#include <AtlCom/ComUtils.h>
#include <shlobj.h>
#include <File/File.h>
#include <Xml/Xml.h>
#include <ODBC/ODBC.h>
#include <CppUnitTests/CppUnitTests.h>
#include <ODBC/MSSQLDatabase.h>
#include <ODBC/AccessDatabase.h>
#include <Crypt/Crypt.h>
