#pragma once

using namespace AppSecInc::Msi::Flags;

static const FlagMapEntry s_LogonTypeFlags[] = 
{
    { L"LOGON32_LOGON_BATCH", LOGON32_LOGON_BATCH },
    { L"LOGON32_LOGON_INTERACTIVE", LOGON32_LOGON_INTERACTIVE },
    { L"LOGON32_LOGON_NETWORK", LOGON32_LOGON_NETWORK },
    { L"LOGON32_LOGON_NETWORK_CLEARTEXT", LOGON32_LOGON_NETWORK_CLEARTEXT },
    { L"LOGON32_LOGON_NEW_CREDENTIALS", LOGON32_LOGON_NEW_CREDENTIALS },
    { L"LOGON32_LOGON_SERVICE", LOGON32_LOGON_SERVICE },
    { L"LOGON32_LOGON_UNLOCK", LOGON32_LOGON_UNLOCK }
};

static const FlagMapEntry s_LogonProviderFlags[] = 
{
    { L"LOGON32_PROVIDER_DEFAULT", LOGON32_PROVIDER_DEFAULT },
    { L"LOGON32_PROVIDER_WINNT50", LOGON32_PROVIDER_WINNT50 },
    { L"LOGON32_PROVIDER_WINNT40", LOGON32_PROVIDER_WINNT40 },
    { L"LOGON32_PROVIDER_WINNT35", LOGON32_PROVIDER_WINNT35 }
};
