#pragma once

using namespace AppSecInc::Msi::Flags;

static const FlagMapEntry s_TcpSocketTypeFlags[] = 
{
    { L"SOCK_STREAM", SOCK_STREAM },
    { L"SOCK_DGRAM", SOCK_DGRAM },
    { L"SOCK_RAW", SOCK_RAW },
    { L"SOCK_RDM", SOCK_RDM },
    { L"SOCK_SEQPACKET", SOCK_SEQPACKET },
};

static const FlagMapEntry s_IpProtocolFlags[] = 
{
    { L"IPPROTO_TCP", IPPROTO_TCP },
    { L"IPPROTO_UDP", IPPROTO_UDP }
};

typedef struct
{
    LPCWSTR name;
    HKEY value;
} FlagMapEntryHKEY;

static const FlagMapEntryHKEY s_RegistryRoot[] = 
{
    { L"HKEY_LOCAL_MACHINE", HKEY_LOCAL_MACHINE },
    { L"HKEY_CURRENT_USER", HKEY_CURRENT_USER },
	{ L"HKEY_CURRENT_CONFIG", HKEY_CURRENT_CONFIG },
	{ L"HKEY_CLASSES_ROOT", HKEY_CLASSES_ROOT },
	{ L"HKEY_USERS", HKEY_USERS }
};

static const FlagMapEntry s_ServiceControl[] = 
{
    { L"SERVICE_CONTROL_START", SERVICE_CONTROL_START },
    { L"SERVICE_CONTROL_STOP", SERVICE_CONTROL_STOP }, 
    { L"SERVICE_CONTROL_PAUSE", SERVICE_CONTROL_PAUSE },
    { L"SERVICE_CONTROL_CONTINUE", SERVICE_CONTROL_CONTINUE },
};

static const FlagMapEntry s_ServiceType[] = 
{
    { L"SERVICE_FILE_SYSTEM_DRIVER", SERVICE_FILE_SYSTEM_DRIVER },
    { L"SERVICE_KERNEL_DRIVER", SERVICE_KERNEL_DRIVER }, 
    { L"SERVICE_WIN32_OWN_PROCESS", SERVICE_WIN32_OWN_PROCESS },
    { L"SERVICE_WIN32_SHARE_PROCESS", SERVICE_WIN32_SHARE_PROCESS },
    { L"SERVICE_INTERACTIVE_PROCESS", SERVICE_INTERACTIVE_PROCESS },
};

static const FlagMapEntry s_ServiceStartType[] = 
{
    { L"SERVICE_AUTO_START", SERVICE_AUTO_START },
    { L"SERVICE_BOOT_START", SERVICE_BOOT_START }, 
    { L"SERVICE_DEMAND_START", SERVICE_DEMAND_START },
    { L"SERVICE_DISABLED", SERVICE_DISABLED },
    { L"SERVICE_SYSTEM_START", SERVICE_SYSTEM_START },
};

static const FlagMapEntry s_ServiceErrorControl[] = 
{
    { L"SERVICE_ERROR_IGNORE", SERVICE_ERROR_IGNORE },
    { L"SERVICE_ERROR_NORMAL", SERVICE_ERROR_NORMAL }, 
    { L"SERVICE_ERROR_SEVERE", SERVICE_ERROR_SEVERE },
    { L"SERVICE_ERROR_CRITICAL", SERVICE_ERROR_CRITICAL },
};
