#pragma once

using namespace AppSecInc::Msi::Flags;

static const FlagMapEntry s_CryptProtectDataFlags[] = 
{
    { L"CRYPTPROTECT_LOCAL_MACHINE", CRYPTPROTECT_LOCAL_MACHINE },
    { L"CRYPTPROTECT_UI_FORBIDDEN", CRYPTPROTECT_UI_FORBIDDEN },
    { L"CRYPTPROTECT_AUDIT", CRYPTPROTECT_AUDIT },
    { L"CRYPTPROTECT_VERIFY_PROTECTION", CRYPTPROTECT_VERIFY_PROTECTION },
};

